- name: Apply haproxy config for triliovault services
  hosts:
    - haproxy
    - '&enable_haproxy_True'
  serial: '{{ kolla_serial|default("0") }}'
  tags:
    - haproxy
  roles:
    - { role: haproxy,
        when: enable_haproxy | bool }
  tasks:
    - include_role:
        name: triliovault
        tasks_from: loadbalancer
      when:
        - inventory_hostname in groups['triliovault-datamover-api']
        - inventory_hostname in groups['triliovault-wlm-api']
        - enable_haproxy | bool
        - enable_triliovault | bool
        - kolla_action in ['deploy', 'reconfigure', 'upgrade', 'config']
    
- name: Apply role triliovault
  gather_facts: false
  hosts:
    - triliovault-datamover-api
    - triliovault-datamover
    - triliovault-wlm-api
    - triliovault-wlm-workloads
    - triliovault-wlm-scheduler
    - triliovault-wlm-cron
  serial: '{{ kolla_serial|default("0") }}'
  roles:
    - { role: triliovault,
        tags: triliovault,
        when: enable_triliovault | bool }